### ISSUE TITLE
Explain how to use cgi-bin

### ISSUE THREAD

**Issue by nichtich** [leejo/cgi-alternatives#11]
This module does not answer how to replace a cgi script located in cgi-bin so it is automatically executed by the webserver. Alternatives that require to "run this script" fail as easy replacement. Adding an appropriate shebang line should help:

    #!/usr/bin/env plackup

**Comment by leejo** [comment]
That's more of a deployment concern, and i'm wary of replicating each frameworks documentation for deployment options. I haven't checked, but would `#!/usr/bin/env plackup` actually do the right thing if this were executed by the webserver? Observe:

```
[leejohnson@lees-macbook-air J0 C7427 14:45:22 * master]
/Users/leejohnson/working/cgi-alternatives/examples > head -n 1 plack_psgi.pl
#!/usr/bin/env plackup

[leejohnson@lees-macbook-air J0 C7427 14:45:24 * master]
/Users/leejohnson/working/cgi-alternatives/examples > ./plack_psgi.pl
HTTP::Server::PSGI: Accepting connections at http://0:5000/
```

Documentation patches welcome however. Ta!
